### ISSUE TITLE
com.unity.settings-manager not mirrored

### ISSUE THREAD

**Issue by rockwalrus** [needle-mirror/needle-mirror.github.io#1]
It looks like [`com.unity.settings-manager`](https://docs.unity3d.com/Packages/com.unity.settings-manager@1.0/manual/index.html) isn't being mirrored, perhaps because it doesn't show up in `com.unity.package-manager.metadata`. It's not clear to me where the Package Manager gets its version information from for that package, but `1.0.0` and `1.0.3` are available in the 2019.4 Package Manager.

Its `package.json` references https://github.com/Unity-Technologies/com.unity.settings-manager, but that seems to be a private repository.

**Comment by marwie** [comment]
Thanks for the heads up, I'll take a look at it

**Comment by marwie** [comment]
Hello, you're right, it was missing in the metadata list. 

I've just added it manually and a new repo has already been created https://github.com/needle-mirror/com.unity.settings-manager  

If everything goes right it should just be / stay up to date :)

**Comment by rockwalrus** [comment]
Excellent!
