### ISSUE TITLE
com.unity.animation package not mirrored

### ISSUE THREAD

**Issue by zdirtywork** [needle-mirror/needle-mirror.github.io#10]
The [com.unity.animation](https://docs.unity3d.com/Packages/com.unity.animation@0.9/manual/index.html) is not mirrored.

Though this package has not been updated for a long time, Unity says it is still under development and not abandoned.

**Comment by hybridherbst** [comment]
Thanks - added now: https://github.com/needle-mirror/com.unity.animation
