### ISSUE TITLE
com.unity.xr.openxr not updating

### ISSUE THREAD

**Issue by sjando** [needle-mirror/needle-mirror.github.io#11]
The mirror for the OpenXR package appears to be stuck at version 1.3.1 from 18+ months ago, but the package has been [updated fairly regularly](https://docs.unity3d.com/Packages/com.unity.xr.openxr@1.8/changelog/CHANGELOG.html) since then.

There's also a couple of new XR-related packages that aren't yet mirrored:
- [com.unity.xr.hands](https://docs.unity3d.com/Packages/com.unity.xr.hands@latest/index.html)
- [com.unity.xr.meta-openxr](https://docs.unity3d.com/Packages/com.unity.xr.meta-openxr@latest/index.html)

Really appreciate this resource btw. Thanks for the excellent work!

**Comment by hybridherbst** [comment]
Hey there!

We know about that package being excluded, at some point Unity changed the format of the package .tgz to something that our mirror backend can't open right now. (It's the only package with that format that we know of)

I added the other two, should show up soon if they don't happen to have the same issue 🤞

**Comment by hybridherbst** [comment]
New repos here:
https://github.com/needle-mirror/com.unity.xr.hands
https://github.com/needle-mirror/com.unity.xr.meta-openxr

**Comment by sjando** [comment]
> Hey there!
> 
> We know about that package being excluded, at some point Unity changed the format of the package .tgz to something that our mirror backend can't open right now. (It's the only package with that format that we know of)
> 
> I added the other two, should show up soon if they don't happen to have the same issue 🤞

Thanks for adding the other two! Could the issue with OpenXR just be a one-off Unity CDN problem with version 1.4.0 specifically (the next version after 1.3.1) where the mirror gets stuck?

Not sure how your mirror backend works but I can successfully do:

```
curl https://download.packages.unity.com/com.unity.xr.openxr/-/com.unity.xr.openxr-X.Y.Z.tgz | tar zx
```

for every known version of the package except 1.4.0 (including 1.4.1 and beyond). 1.4.0 alone breaks, not because of the archive content, but because the CDN returns an XML error message instead of the actual archive.

I also note that 1.4.0 is excluded from the current CHANGELOG.md file and that in the package metadata versions 1.4.0 and 1.4.1 have identical values for upm.changelog, as though 1.4.0 is a known broken/revoked release.

**Comment by hybridherbst** [comment]
Good point, may be! I don't think we can skip individual versions via config right now (the assumption was "Unity doesn't upload and then keep entirely broken files"), so some changes on our end are needed to actually skip.

(or can we @marwie? maybe if we create an commit/tag in question manually?)

**Comment by marwie** [comment]
Sorry for taking so long but this has been fixed as of yesterday.
