### ISSUE TITLE
com.unity.ide.visualstudio not mirrored

### ISSUE THREAD

**Issue by rockwalrus** [needle-mirror/needle-mirror.github.io#2]
It looks like [`com.unity.ide.visualstudio`](https://docs.unity3d.com/2020.2/Documentation/Manual/com.unity.ide.visualstudio.html) isn't being mirrored either.

**Comment by marwie** [comment]
Thanks for the info, added now https://github.com/needle-mirror/com.unity.ide.visualstudio
