### ISSUE TITLE
Mono Cecil packages not mirrored

### ISSUE THREAD

**Issue by rockwalrus** [needle-mirror/needle-mirror.github.io#3]
For completeness, `nuget.mono-cecil` and `com.unity.nuget.mono-cecil`, which are depended upon by some Unity packages, should be included.

**Comment by marwie** [comment]
Thanks! Both added
https://github.com/needle-mirror/nuget.mono-cecil
https://github.com/needle-mirror/com.unity.nuget.mono-cecil
