### ISSUE TITLE
com.unity.roslyn has an old tag that is dated 2027

### ISSUE THREAD

**Issue by sbergen** [needle-mirror/needle-mirror.github.io#7]
The [latest tag for com.unity.roslyn](https://github.com/needle-mirror/com.unity.roslyn/releases/tag/0.2.1-preview) has a date in 2027, which I believe is messing up some feed readers. I'm not 100% sure this is the cause, but I believe this is the reason at least the Slack RSS integration (which we've been using) hasn't been working for quite some time, as the `updated` tag has been stuck at 2027-01-21T00:00:00Z.

I understand this issue probably originates from a bad changelog from Unity, but it looks like it has since been fixed: https://docs.unity3d.com/Packages/com.unity.roslyn@0.2/changelog/CHANGELOG.html

Thanks for making this tool, and sorry for having to deal with Unity's buggy changelogs :)

**Comment by marwie** [comment]
Hello, thanks for reporting - altough can you report this error to Unity directly? 
Otherwise it will sadly not reach the correct people

https://support.unity.com/hc/en-us/articles/206336985-How-do-I-submit-a-bug-report-
