### ISSUE TITLE
Nothing is displayed - white page

### ISSUE THREAD

**Issue by kipash** [needle-mirror/needle-mirror.github.io#8]
Reproduced in Firefox, Opera and Chrome.

First, it can't fetch a "custom.css". Perhaps while rebuilding the needle.tools website the CSS got moved?
`GET https://needle.tools/css/custom.css net::ERR_ABORTED 404`

Second, it doesn't know what "marked" method is which is essential to display anything.
`Uncaught (in promise) TypeError: marked is not a function`

**Comment by hybridherbst** [comment]
Better late than never :) fixed.
